# Generated by Django 6.0.4 on 2026-07-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0006_alter_activity_meeting_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='meeting_provider',
            field=models.CharField(blank=True, choices=[('zoom', 'Zoom'), ('google_meet', 'Google Meet'), ('ms_teams', 'Microsoft Teams')], max_length=30, null=True, verbose_name='Meeting Provider'),
        ),
    ]
