# Generated by Django 6.0.4 on 2026-08-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0007_alter_activity_meeting_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='additional_info',
            field=models.JSONField(blank=True, null=True, verbose_name='Additional Info'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='call_duration_seconds',
            field=models.IntegerField(blank=True, null=True, verbose_name='Call Duration (seconds)'),
        ),
    ]
