# Generated by Django 6.0.4 on 2026-07-22 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_businesshour_options_businesshour_holidays_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportschedule',
            name='fields',
            field=models.JSONField(blank=True, default=dict, help_text='Dict of {model_name: [field_name, ...]}. Empty/missing entries export all exportable fields for that model.', verbose_name='Fields'),
        ),
    ]
