# Generated by Django 6.0.4 on 2026-08-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_exportschedule_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businesshour",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="horillaattachment",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="shifthour",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
    ]
