# Generated by Django 6.0.4 on 2026-08-13 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_businesshour_name_and_more'),
        ('core', '0004_alter_businesshour_time_zone_alter_company_time_zone_and_more'),
    ]

    operations = [
    ]
