# Generated by Django 6.0.4 on 2026-08-20 05:51

import json

import multiselectfield.db.fields
from django.conf import settings
from django.core.exceptions import FieldDoesNotExist
from django.db import migrations, models
from django.db.models import Case, When, Value

NUMBER_GROUPING_TO_FORMAT = {
    "0": "western_format",
    "3,0": "western_format",
    "3,2,0": "indian_format",
    "4,0": "space_format",
}

# Reverse mapping, built once at import time instead of on every call.
FORMAT_TO_GROUPING = {
    new_value: old_value for old_value, new_value in NUMBER_GROUPING_TO_FORMAT.items()
}

OLD_FIELD = "number_grouping"
NEW_FIELD = "number_format"
OLD_DISPLAY = f"get_{OLD_FIELD}_display"
NEW_DISPLAY = f"get_{NEW_FIELD}_display"


def _has_field(model, field_name):
    # O(1) dict lookup instead of scanning model._meta.get_fields()
    # (which also builds the reverse-relation cache).
    try:
        model._meta.get_field(field_name)
        return True
    except FieldDoesNotExist:
        return False


def _auth_user_parts():
    return settings.AUTH_USER_MODEL.split(".")


def _user_model_identity(apps):
    """
    Resolve labels for whatever AUTH_USER_MODEL is configured
    (default HorillaUser or any custom user model).
    """
    app_label, model = _auth_user_parts()
    User = apps.get_model(app_label, model)
    meta = User._meta
    names = {
        meta.model_name.lower(),
        meta.object_name.lower(),
        model.lower(),
    }
    qualified = {
        settings.AUTH_USER_MODEL.lower(),
        f"{app_label}.{model}".lower(),
        f"{meta.app_label}.{meta.model_name}".lower(),
        f"{meta.app_label}.{meta.object_name}".lower(),
    }
    return {
        "app_label": meta.app_label.lower(),
        "names": names,
        "qualified": qualified,
    }


def _is_user_model_ref(apps, model_name, app_label=None):
    """
    True when model_name (/ optional app_label) refers to AUTH_USER_MODEL.

    Accepts bare names (CustomUser) or qualified (accounts.customuser).
    """
    if not model_name:
        return False

    identity = _user_model_identity(apps)
    name = str(model_name).strip()
    name_l = name.lower()
    short_l = name_l.split(".")[-1]

    if "." in name_l:
        return name_l in identity["qualified"]

    if short_l not in identity["names"]:
        return False
    if app_label is not None and str(app_label).strip():
        return str(app_label).lower() == identity["app_label"]
    return True


def _rename_field_token(name, old, new):
    """Rename a bare field name or its get_*_display variant."""
    if name == old:
        return new
    if name == f"get_{old}_display":
        return f"get_{new}_display"
    return name


def _rename_in_field_list(items, old, new):
    """
    Rename field refs in JSON lists.

    Supports plain names and [verbose_name, field_name] pairs.
    """
    if not isinstance(items, list):
        return items, False

    changed = False
    updated = []
    for item in items:
        if isinstance(item, (list, tuple)) and len(item) >= 2:
            field_name = item[1]
            renamed = _rename_field_token(field_name, old, new)
            if renamed != field_name:
                changed = True
                updated.append([item[0], renamed, *list(item[2:])])
            else:
                updated.append(list(item) if isinstance(item, tuple) else item)
        elif isinstance(item, str):
            renamed = _rename_field_token(item, old, new)
            if renamed != item:
                changed = True
            updated.append(renamed)
        else:
            updated.append(item)
    return updated, changed


def _rename_dict_keys(mapping, old, new):
    """Rename top-level keys that match the old field name / display helper."""
    if not isinstance(mapping, dict):
        return mapping, False

    changed = False
    updated = {}
    for key, value in mapping.items():
        new_key = _rename_field_token(key, old, new) if isinstance(key, str) else key
        if new_key != key:
            changed = True
        # Prefer the renamed key if both old and new somehow exist.
        if new_key in updated and key == old:
            continue
        updated[new_key] = value
    return updated, changed


def _rename_filter_params(filter_params, old, new):
    """
    SavedFilterList stores field names under the 'field' list, e.g.:
    {"field": ["number_grouping"], "operator": ["exact"], "value": ["0"]}
    """
    if not isinstance(filter_params, dict):
        return filter_params, False

    changed = False
    updated = dict(filter_params)
    fields = updated.get("field")
    if isinstance(fields, list):
        new_fields = []
        for name in fields:
            if isinstance(name, str):
                renamed = _rename_field_token(name, old, new)
                if renamed != name:
                    changed = True
                new_fields.append(renamed)
            else:
                new_fields.append(name)
        updated["field"] = new_fields
    return updated, changed


def _map_grouping_value(value, mapping):
    if value is None:
        return None
    text = str(value)
    return mapping.get(text, value)


def migrate_number_grouping_forward(apps, schema_editor):
    app_label, model_name = _auth_user_parts()
    User = apps.get_model(app_label, model_name)

    if not _has_field(User, OLD_FIELD):
        return

    User.objects.exclude(number_grouping__isnull=True).update(
        number_format=Case(
            *[
                When(number_grouping=old_value, then=Value(new_value))
                for old_value, new_value in NUMBER_GROUPING_TO_FORMAT.items()
            ],
            default=models.F("number_format"),
        )
    )


def migrate_number_grouping_backward(apps, schema_editor):
    app_label, model_name = _auth_user_parts()
    User = apps.get_model(app_label, model_name)
    if not _has_field(User, OLD_FIELD):
        return

    User.objects.update(
        number_grouping=Case(
            *[
                When(number_format=new_value, then=Value(old_value))
                for new_value, old_value in FORMAT_TO_GROUPING.items()
            ],
            default=models.F("number_grouping"),
        )
    )


def _migrate_list_column_visibility(apps, old, new):
    ListColumnVisibility = apps.get_model("core", "ListColumnVisibility")
    for row in ListColumnVisibility.all_objects.all().iterator():
        if not _is_user_model_ref(apps, row.model_name, row.app_label):
            continue
        visible, v_changed = _rename_in_field_list(row.visible_fields or [], old, new)
        removed, r_changed = _rename_in_field_list(
            row.removed_custom_fields or [], old, new
        )
        if v_changed or r_changed:
            row.visible_fields = visible
            row.removed_custom_fields = removed
            row.save(update_fields=["visible_fields", "removed_custom_fields"])


def _migrate_field_permission(apps, old, new):
    FieldPermission = apps.get_model("core", "FieldPermission")
    ContentType = apps.get_model("contenttypes", "ContentType")
    user_app, user_model = _auth_user_parts()
    User = apps.get_model(user_app, user_model)

    try:
        ct = ContentType.objects.get(
            app_label=User._meta.app_label, model=User._meta.model_name
        )
    except ContentType.DoesNotExist:
        return

    for perm in FieldPermission.objects.filter(
        content_type=ct, field_name=old
    ).iterator():
        # Avoid unique_together collisions if a target row already exists.
        conflict_qs = FieldPermission.objects.filter(
            content_type=ct, field_name=new, user=perm.user, role=perm.role
        )
        if conflict_qs.exists():
            perm.delete()
        else:
            perm.field_name = new
            perm.save(update_fields=["field_name"])


def _migrate_saved_filter_list(apps, old, new):
    SavedFilterList = apps.get_model("core", "SavedFilterList")
    for row in SavedFilterList.all_objects.all().iterator():
        if not _is_user_model_ref(apps, row.model_name):
            continue
        params, changed = _rename_filter_params(row.filter_params or {}, old, new)
        if changed:
            row.filter_params = params
            row.save(update_fields=["filter_params"])


def _migrate_kanban_group_by(apps, old, new):
    KanbanGroupBy = apps.get_model("core", "KanbanGroupBy")
    for row in KanbanGroupBy.all_objects.filter(field_name=old).iterator():
        if not _is_user_model_ref(apps, row.model_name, row.app_label):
            continue
        # unique_together: model_name, app_label, user, view_type
        conflict = (
            KanbanGroupBy.all_objects.filter(
                model_name=row.model_name,
                app_label=row.app_label,
                user_id=row.user_id,
                view_type=row.view_type,
                field_name=new,
            )
            .exclude(pk=row.pk)
            .exists()
        )
        if conflict:
            row.delete()
        else:
            row.field_name = new
            row.save(update_fields=["field_name"])


def _migrate_recycle_bin(apps, old, new, value_map):
    """Rename field key in archived user JSON; map stored values when remapping."""
    RecycleBin = apps.get_model("core", "RecycleBin")

    for row in RecycleBin.objects.all().iterator():
        if not _is_user_model_ref(apps, row.model_name):
            continue
        try:
            data = json.loads(row.data) if row.data else {}
        except (TypeError, ValueError, json.JSONDecodeError):
            continue
        if not isinstance(data, dict) or old not in data:
            continue

        raw_value = data.pop(old)
        data[new] = (
            _map_grouping_value(raw_value, value_map) if value_map else raw_value
        )

        row.data = json.dumps(data)
        row.save(update_fields=["data"])


def _migrate_import_history(apps, old, new):
    ImportHistory = apps.get_model("core", "ImportHistory")
    for row in ImportHistory.objects.all().iterator():
        if not _is_user_model_ref(
            apps, row.module_name, getattr(row, "app_label", None)
        ):
            continue

        changed = False
        match_fields = row.match_fields or []
        if isinstance(match_fields, list):
            new_match, m_changed = _rename_in_field_list(match_fields, old, new)
            if m_changed:
                row.match_fields = new_match
                changed = True

        mappings = row.field_mappings or {}
        new_mappings, map_changed = _rename_dict_keys(mappings, old, new)
        if map_changed:
            row.field_mappings = new_mappings
            changed = True

        if changed:
            row.save(update_fields=["match_fields", "field_mappings"])


def _migrate_export_schedule(apps, old, new):
    ExportSchedule = apps.get_model("core", "ExportSchedule")
    for row in ExportSchedule.objects.all().iterator():
        fields = row.fields or {}
        if not isinstance(fields, dict):
            continue

        changed = False
        updated = {}
        for model_key, field_list in fields.items():
            if _is_user_model_ref(apps, model_key) and isinstance(field_list, list):
                new_list, list_changed = _rename_in_field_list(field_list, old, new)
                updated[model_key] = new_list
                changed = changed or list_changed
            else:
                updated[model_key] = field_list

        if changed:
            row.fields = updated
            row.save(update_fields=["fields"])


def migrate_stored_field_names_forward(apps, schema_editor):
    """Rename stored number_grouping field-name refs to number_format."""
    _migrate_list_column_visibility(apps, OLD_FIELD, NEW_FIELD)
    _migrate_field_permission(apps, OLD_FIELD, NEW_FIELD)
    _migrate_saved_filter_list(apps, OLD_FIELD, NEW_FIELD)
    _migrate_kanban_group_by(apps, OLD_FIELD, NEW_FIELD)
    _migrate_recycle_bin(apps, OLD_FIELD, NEW_FIELD, NUMBER_GROUPING_TO_FORMAT)
    _migrate_import_history(apps, OLD_FIELD, NEW_FIELD)
    _migrate_export_schedule(apps, OLD_FIELD, NEW_FIELD)


def migrate_stored_field_names_backward(apps, schema_editor):
    """Restore stored number_format field-name refs to number_grouping."""
    _migrate_list_column_visibility(apps, NEW_FIELD, OLD_FIELD)
    _migrate_field_permission(apps, NEW_FIELD, OLD_FIELD)
    _migrate_saved_filter_list(apps, NEW_FIELD, OLD_FIELD)
    _migrate_kanban_group_by(apps, NEW_FIELD, OLD_FIELD)
    _migrate_recycle_bin(apps, NEW_FIELD, OLD_FIELD, FORMAT_TO_GROUPING)
    _migrate_import_history(apps, NEW_FIELD, OLD_FIELD)
    _migrate_export_schedule(apps, NEW_FIELD, OLD_FIELD)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_businesshour_time_zone_alter_company_time_zone_and_more"),
    ]

    operations = [
        # 1. Add the new field first...
        migrations.AddField(
            model_name="horillauser",
            name="number_format",
            field=models.CharField(
                choices=[
                    ("western_format", "Western - 1,234,567.89"),
                    ("european_format", "European - 1.234.567,89"),
                    ("space_format", "Space Separated - 1 234 567,89"),
                    ("indian_format", "Indian - 12,34,567.89"),
                ],
                default="western_format",
                help_text="Select your preferred number format.",
                max_length=20,
                verbose_name="Number Format",
            ),
        ),
        # 2. ...populate it from the old field while both still exist...
        migrations.RunPython(
            migrate_number_grouping_forward, migrate_number_grouping_backward
        ),
        # 3. ...rename stored field-name references in preference / history tables...
        migrations.RunPython(
            migrate_stored_field_names_forward, migrate_stored_field_names_backward
        ),
        # 4. ...then remove the old fields.
        migrations.RemoveField(
            model_name="horillauser",
            name="number_grouping",
        ),
        migrations.RemoveField(
            model_name="multiplecurrency",
            name="format",
        ),
        migrations.AlterField(
            model_name="businesshour",
            name="week_days",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("sun", "Sunday"),
                    ("mon", "Monday"),
                    ("tue", "Tuesday"),
                    ("wed", "Wednesday"),
                    ("thu", "Thursday"),
                    ("fri", "Friday"),
                    ("sat", "Saturday"),
                ],
                max_length=27,
                verbose_name="Week days",
            ),
        ),
        migrations.AlterField(
            model_name="shifthour",
            name="week_days",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("sun", "Sunday"),
                    ("mon", "Monday"),
                    ("tue", "Tuesday"),
                    ("wed", "Wednesday"),
                    ("thu", "Thursday"),
                    ("fri", "Friday"),
                    ("sat", "Saturday"),
                ],
                max_length=27,
                verbose_name="Week days",
            ),
        ),
    ]

