# Generated by Django 6.0.4 on 2026-08-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0002_alter_shortcutkey_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortcutkey',
            name='additional_info',
            field=models.JSONField(blank=True, null=True, verbose_name='Additional Info'),
        ),
    ]
