# Generated by Django 6.0.4 on 2026-08-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_reviewprocess_unique_active_review_process_per_model_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewcondition',
            name='additional_info',
            field=models.JSONField(blank=True, null=True, verbose_name='Additional Info'),
        ),
        migrations.AlterField(
            model_name='reviewjob',
            name='additional_info',
            field=models.JSONField(blank=True, null=True, verbose_name='Additional Info'),
        ),
        migrations.AlterField(
            model_name='reviewprocess',
            name='additional_info',
            field=models.JSONField(blank=True, null=True, verbose_name='Additional Info'),
        ),
        migrations.AlterField(
            model_name='reviewrule',
            name='additional_info',
            field=models.JSONField(blank=True, null=True, verbose_name='Additional Info'),
        ),
        migrations.AlterField(
            model_name='reviewrulecondition',
            name='additional_info',
            field=models.JSONField(blank=True, null=True, verbose_name='Additional Info'),
        ),
    ]
