# Generated by Django 6.0.4 on 2026-07-22 04:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("approvals", "0003_remove_approvalrule_process_config"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="approvalinstance",
            name="delegated_approver",
            field=models.ForeignKey(
                blank=True,
                help_text="When set, overrides current_step's approver for this instance only, without altering the shared process rule's step configuration.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="delegated_approval_instances",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
