# Generated by Django 6.0.4 on 2026-08-28 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0004_approvalinstance_delegated_approver'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approvaldecision',
            options={'ordering': ['-decided_at', '-id'], 'verbose_name': 'Approval Decision', 'verbose_name_plural': 'Approval Decisions'},
        ),
        migrations.AlterModelOptions(
            name='approvalinstance',
            options={'verbose_name': 'Approval Instance', 'verbose_name_plural': 'Approval Instances'},
        ),
        migrations.AlterModelOptions(
            name='approvalprocessrule',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Approval Process Rule', 'verbose_name_plural': 'Approval Process Rules'},
        ),
        migrations.AlterModelOptions(
            name='approvalrule',
            options={'verbose_name': 'Approval Process', 'verbose_name_plural': 'Approval Processes'},
        ),
        migrations.AlterModelOptions(
            name='approvalstep',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Approval Step', 'verbose_name_plural': 'Approval Steps'},
        ),
        migrations.AlterField(
            model_name='approvalcondition',
            name='additional_info',
            field=models.JSONField(blank=True, null=True, verbose_name='Additional Info'),
        ),
        migrations.AlterField(
            model_name='approvalcondition',
            name='approval_process_rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='approvals.approvalprocessrule', verbose_name='Process Rule'),
        ),
        migrations.AlterField(
            model_name='approvaldecision',
            name='additional_info',
            field=models.JSONField(blank=True, null=True, verbose_name='Additional Info'),
        ),
        migrations.AlterField(
            model_name='approvalinstance',
            name='additional_info',
            field=models.JSONField(blank=True, null=True, verbose_name='Additional Info'),
        ),
        migrations.AlterField(
            model_name='approvalprocessrule',
            name='additional_info',
            field=models.JSONField(blank=True, null=True, verbose_name='Additional Info'),
        ),
        migrations.AlterField(
            model_name='approvalprocessrule',
            name='approval_process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_rules', to='approvals.approvalrule', verbose_name='Approval Process'),
        ),
        migrations.AlterField(
            model_name='approvalrule',
            name='additional_info',
            field=models.JSONField(blank=True, null=True, verbose_name='Additional Info'),
        ),
        migrations.AlterField(
            model_name='approvalrule',
            name='trigger_on_create',
            field=models.BooleanField(default=True, help_text='Run this process when a new record is created.', verbose_name='When Record Is Created'),
        ),
        migrations.AlterField(
            model_name='approvalrule',
            name='trigger_on_edit',
            field=models.BooleanField(default=False, help_text='Run this process when a record is edited.', verbose_name='When Record Is Edited'),
        ),
        migrations.AlterField(
            model_name='approvalstep',
            name='additional_info',
            field=models.JSONField(blank=True, null=True, verbose_name='Additional Info'),
        ),
    ]
