# Generated by Django 6.0.4 on 2026-07-11 13:18

import django.db.models.deletion
import horilla.contrib.mail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0002_alter_businesshour_options_businesshour_holidays_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CallIntegrationSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "additional_info",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Additional info"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "is_enabled",
                    models.BooleanField(default=False, verbose_name="Enabled"),
                ),
                (
                    "access_type",
                    models.CharField(
                        choices=[
                            ("all", "All Users"),
                            ("roles", "Specific Roles"),
                            ("users", "Specific Users"),
                        ],
                        default="all",
                        help_text="Who can initiate calls.",
                        max_length=10,
                        verbose_name="Access Type",
                    ),
                ),
                (
                    "allowed_roles",
                    models.ManyToManyField(
                        blank=True,
                        related_name="call_integrations",
                        to="core.role",
                        verbose_name="Allowed Roles",
                    ),
                ),
                (
                    "allowed_users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="call_integrations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Allowed Users",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Call Integration Setting",
                "verbose_name_plural": "Call Integration Settings",
            },
        ),
        migrations.CreateModel(
            name="CallProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "additional_info",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Additional info"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "provider_type",
                    models.CharField(
                        choices=[
                            ("twilio", "Twilio"),
                            ("exotel", "Exotel"),
                            ("asterisk", "Asterisk / FreePBX"),
                            ("three_cx", "3CX"),
                            ("custom", "Custom / Generic SIP"),
                        ],
                        max_length=20,
                        verbose_name="Provider",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("testing", "Testing"),
                        ],
                        default="inactive",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "account_sid",
                    horilla.contrib.mail.fields.EncryptedCharField(
                        blank=True,
                        help_text="Twilio AccountSID, Exotel SID, or equivalent identifier.",
                        max_length=512,
                        verbose_name="Account SID / App ID",
                    ),
                ),
                (
                    "api_key",
                    horilla.contrib.mail.fields.EncryptedCharField(
                        blank=True, max_length=512, verbose_name="API Key"
                    ),
                ),
                (
                    "api_secret",
                    horilla.contrib.mail.fields.EncryptedCharField(
                        blank=True,
                        max_length=512,
                        verbose_name="API Secret / Auth Token",
                    ),
                ),
                (
                    "api_base_url",
                    models.URLField(
                        blank=True,
                        help_text="Required for Asterisk/3CX/custom SIP REST endpoints.",
                        max_length=500,
                        verbose_name="API Base URL",
                    ),
                ),
                (
                    "caller_id",
                    models.CharField(
                        blank=True,
                        help_text="Default outbound phone number or SIP caller ID.",
                        max_length=40,
                        verbose_name="Default Caller ID",
                    ),
                ),
                (
                    "webhook_secret",
                    horilla.contrib.mail.fields.EncryptedCharField(
                        blank=True,
                        help_text="Used to validate incoming webhook signatures.",
                        max_length=255,
                        verbose_name="Webhook Secret",
                    ),
                ),
                (
                    "extra_config",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Extra Configuration"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Call Provider",
                "verbose_name_plural": "Call Providers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AgentMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "additional_info",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Additional info"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "extension",
                    models.CharField(
                        blank=True,
                        max_length=40,
                        verbose_name="Extension / SIP Extension",
                    ),
                ),
                (
                    "agent_id",
                    models.CharField(
                        blank=True,
                        help_text="Provider's internal agent or caller identifier.",
                        max_length=100,
                        verbose_name="Agent / Caller ID",
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="Available"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="call_agent_mappings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_mappings",
                        to="calls.callprovider",
                        verbose_name="Provider",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent Mapping",
                "verbose_name_plural": "Agent Mappings",
                "unique_together": {("provider", "user")},
            },
        ),
        migrations.CreateModel(
            name="CallLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "additional_info",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Additional info"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("inbound", "Inbound"), ("outbound", "Outbound")],
                        max_length=20,
                        verbose_name="Direction",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initiated", "Initiated"),
                            ("ringing", "Ringing"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("no_answer", "No Answer"),
                            ("busy", "Busy"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="initiated",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "from_number",
                    models.CharField(max_length=40, verbose_name="From Number"),
                ),
                (
                    "to_number",
                    models.CharField(max_length=40, verbose_name="To Number"),
                ),
                (
                    "duration_seconds",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Duration (seconds)"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Started At"
                    ),
                ),
                (
                    "ended_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Ended At"
                    ),
                ),
                (
                    "provider_call_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Twilio CallSID, Exotel CallSid, etc.",
                        max_length=255,
                        verbose_name="Provider Call ID",
                    ),
                ),
                (
                    "recording_url",
                    models.URLField(
                        blank=True,
                        max_length=2000,
                        null=True,
                        verbose_name="Recording URL",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                (
                    "related_model_name",
                    models.CharField(
                        blank=True,
                        help_text="'lead' or 'contact'",
                        max_length=50,
                        verbose_name="Related Model",
                    ),
                ),
                (
                    "related_object_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Related Object ID"
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="call_logs",
                        to="calls.agentmapping",
                        verbose_name="Agent",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="call_logs",
                        to="calls.callprovider",
                        verbose_name="Provider",
                    ),
                ),
            ],
            options={
                "verbose_name": "Call Log",
                "verbose_name_plural": "Call Logs",
                "ordering": ["-started_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["provider_call_id"],
                        name="calls_calll_provide_7e51cf_idx",
                    ),
                    models.Index(
                        fields=["status"], name="calls_calll_status_3d30eb_idx"
                    ),
                    models.Index(
                        fields=["from_number"], name="calls_calll_from_nu_277f1e_idx"
                    ),
                    models.Index(
                        fields=["to_number"], name="calls_calll_to_numb_4e24dd_idx"
                    ),
                    models.Index(
                        fields=["started_at"], name="calls_calll_started_b47898_idx"
                    ),
                    models.Index(
                        fields=["company", "started_at"],
                        name="calls_calll_company_821c59_idx",
                    ),
                    models.Index(
                        fields=["company", "status"],
                        name="calls_calll_company_5f58a2_idx",
                    ),
                ],
            },
        ),
    ]
