# Generated by Django 6.0.4 on 2026-07-11 13:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("calls", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="callprovider",
            name="notes",
        ),
    ]
