# Generated by Django 6.0.4 on 2026-07-11 13:18

import horilla.contrib.mail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calls", "0002_remove_callprovider_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calllog",
            name="provider_call_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Twilio CallSID, Plivo RequestUUID, Vonage UUID, Ozonetel UCID, etc.",
                max_length=255,
                verbose_name="Provider Call ID",
            ),
        ),
        migrations.AlterField(
            model_name="callprovider",
            name="account_sid",
            field=horilla.contrib.mail.fields.EncryptedCharField(
                blank=True,
                help_text="Twilio AccountSID, Plivo Auth ID, Ozonetel username, or equivalent identifier.",
                max_length=512,
                verbose_name="Account SID / App ID",
            ),
        ),
        migrations.AlterField(
            model_name="callprovider",
            name="api_base_url",
            field=models.URLField(
                blank=True,
                help_text="Optional override for Ozonetel or custom API endpoints.",
                max_length=500,
                verbose_name="API Base URL",
            ),
        ),
        migrations.AlterField(
            model_name="callprovider",
            name="provider_type",
            field=models.CharField(
                choices=[
                    ("twilio", "Twilio"),
                    ("signalwire", "SignalWire (Beta)"),
                    ("telnyx", "Telnyx (Beta)"),
                    ("sinch", "Sinch (Beta)"),
                    ("exotel", "Exotel (Beta)"),
                    ("mock", "Mock (Testing)"),
                ],
                max_length=20,
                verbose_name="Provider",
            ),
        ),
    ]
