# Generated by Django 6.0.4 on 2026-07-11 13:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("calls", "0003_alter_calllog_provider_call_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agentmapping",
            name="is_available",
        ),
    ]
