# Generated by Django 6.0.4 on 2026-07-11 13:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("calls", "0004_remove_agentmapping_is_available"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="calllog",
            name="notes",
        ),
    ]
