# Generated by Django 6.0.4 on 2026-07-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calls", "0005_remove_calllog_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="callprovider",
            name="recording_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Record calls via this provider. Requires recording support on the provider side.",
                verbose_name="Enable Call Recording",
            ),
        ),
    ]
