# Generated by Django 6.0.4 on 2026-08-25 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0007_activitycallextension'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivityCallExtension',
        ),
    ]
