# Generated by Django 6.0.4 on 2026-08-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0008_delete_activitycallextension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentmapping',
            name='additional_info',
            field=models.JSONField(blank=True, null=True, verbose_name='Additional Info'),
        ),
        migrations.AlterField(
            model_name='callintegrationsetting',
            name='additional_info',
            field=models.JSONField(blank=True, null=True, verbose_name='Additional Info'),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='additional_info',
            field=models.JSONField(blank=True, null=True, verbose_name='Additional Info'),
        ),
        migrations.AlterField(
            model_name='callprovider',
            name='additional_info',
            field=models.JSONField(blank=True, null=True, verbose_name='Additional Info'),
        ),
    ]
