# Generated by Django 6.0.4 on 2026-08-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast',
            name='additional_info',
            field=models.JSONField(blank=True, null=True, verbose_name='Additional Info'),
        ),
        migrations.AlterField(
            model_name='forecastcondition',
            name='additional_info',
            field=models.JSONField(blank=True, null=True, verbose_name='Additional Info'),
        ),
        migrations.AlterField(
            model_name='forecasttarget',
            name='additional_info',
            field=models.JSONField(blank=True, null=True, verbose_name='Additional Info'),
        ),
        migrations.AlterField(
            model_name='forecasttargetuser',
            name='additional_info',
            field=models.JSONField(blank=True, null=True, verbose_name='Additional Info'),
        ),
        migrations.AlterField(
            model_name='forecasttype',
            name='additional_info',
            field=models.JSONField(blank=True, null=True, verbose_name='Additional Info'),
        ),
    ]
