# Generated by Django 6.0.4 on 2026-09-02 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0002_alter_forecast_additional_info_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='forecast',
                    name='created_at',
                    field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At'),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='CREATE INDEX IF NOT EXISTS "forecast_forecast_created_at_3f8125a8" ON "forecast_forecast" ("created_at")',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='forecast',
                    name='is_active',
                    field=models.BooleanField(db_index=True, default=True, verbose_name='Is Active'),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='CREATE INDEX IF NOT EXISTS "forecast_forecast_is_active_f355539b" ON "forecast_forecast" ("is_active")',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='forecastcondition',
                    name='created_at',
                    field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At'),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='CREATE INDEX IF NOT EXISTS "forecast_forecastcondition_created_at_4b18a1c5" ON "forecast_forecastcondition" ("created_at")',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='forecastcondition',
                    name='is_active',
                    field=models.BooleanField(db_index=True, default=True, verbose_name='Is Active'),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='CREATE INDEX IF NOT EXISTS "forecast_forecastcondition_is_active_872f609b" ON "forecast_forecastcondition" ("is_active")',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='forecasttarget',
                    name='created_at',
                    field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At'),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='CREATE INDEX IF NOT EXISTS "forecast_forecasttarget_created_at_2db6371b" ON "forecast_forecasttarget" ("created_at")',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='forecasttarget',
                    name='is_active',
                    field=models.BooleanField(db_index=True, default=True, verbose_name='Is Active'),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='CREATE INDEX IF NOT EXISTS "forecast_forecasttarget_is_active_564a6a31" ON "forecast_forecasttarget" ("is_active")',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='forecasttargetuser',
                    name='created_at',
                    field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At'),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='CREATE INDEX IF NOT EXISTS "forecast_forecasttargetuser_created_at_89e64d10" ON "forecast_forecasttargetuser" ("created_at")',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='forecasttargetuser',
                    name='is_active',
                    field=models.BooleanField(db_index=True, default=True, verbose_name='Is Active'),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='CREATE INDEX IF NOT EXISTS "forecast_forecasttargetuser_is_active_dc07d702" ON "forecast_forecasttargetuser" ("is_active")',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='forecasttype',
                    name='created_at',
                    field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At'),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='CREATE INDEX IF NOT EXISTS "forecast_forecasttype_created_at_5c64f991" ON "forecast_forecasttype" ("created_at")',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='forecasttype',
                    name='is_active',
                    field=models.BooleanField(db_index=True, default=True, verbose_name='Is Active'),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='CREATE INDEX IF NOT EXISTS "forecast_forecasttype_is_active_7d81c359" ON "forecast_forecasttype" ("is_active")',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
    ]
