# Generated by Django 6.0.4 on 2026-08-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflowaction",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("update_field", "Edit Field"),
                    ("assign_task", "Assign Task"),
                    ("email", "Email"),
                    ("notification", "Notification"),
                ],
                max_length=20,
                verbose_name="Action",
            ),
        ),
        migrations.AlterField(
            model_name="workflowtimetriggeraction",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("update_field", "Edit Field"),
                    ("assign_task", "Assign Task"),
                    ("email", "Email"),
                    ("notification", "Notification"),
                ],
                max_length=20,
                verbose_name="Action Type",
            ),
        ),
    ]
