# Generated by Django 6.0.4 on 2026-08-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_alter_workflowaction_action_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledworkflowexecution',
            name='additional_info',
            field=models.JSONField(blank=True, null=True, verbose_name='Additional Info'),
        ),
        migrations.AlterField(
            model_name='workflowaction',
            name='additional_info',
            field=models.JSONField(blank=True, null=True, verbose_name='Additional Info'),
        ),
        migrations.AlterField(
            model_name='workflowcondition',
            name='additional_info',
            field=models.JSONField(blank=True, null=True, verbose_name='Additional Info'),
        ),
        migrations.AlterField(
            model_name='workflowrule',
            name='additional_info',
            field=models.JSONField(blank=True, null=True, verbose_name='Additional Info'),
        ),
        migrations.AlterField(
            model_name='workflowrule',
            name='trigger_on_create',
            field=models.BooleanField(default=True, help_text='Run this workflow when a new record is created.', verbose_name='When Record Is Created'),
        ),
        migrations.AlterField(
            model_name='workflowrule',
            name='trigger_on_edit',
            field=models.BooleanField(default=False, help_text='Run this workflow when an existing record is edited.', verbose_name='When Record Is Edited'),
        ),
        migrations.AlterField(
            model_name='workflowtimetriggeraction',
            name='additional_info',
            field=models.JSONField(blank=True, null=True, verbose_name='Additional Info'),
        ),
    ]
