# Generated by Django 6.0.4 on 2026-08-14 15:34

import horilla.extension.models.migration_ops
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0006_alter_businesshour_time_zone_alter_company_time_zone_and_more"),
    ]

    operations = [
        horilla.extension.models.migration_ops.InjectField(
            target_app_label='core',
            model_name='horillauser',
            name='calendar_system',
            field=models.CharField(choices=[('jalali', 'Shamsi (Jalali)'), ('gregorian', 'Gregorian')], default='jalali', help_text='Choose Shamsi (Jalali) or Gregorian dates when your language is Persian.', max_length=20, verbose_name='Calendar System'),
        ),
    ]
