# Generated by Django 6.0.4 on 2026-08-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customcalendar',
            name='additional_info',
            field=models.JSONField(blank=True, null=True, verbose_name='Additional Info'),
        ),
        migrations.AlterField(
            model_name='customcalendarcondition',
            name='additional_info',
            field=models.JSONField(blank=True, null=True, verbose_name='Additional Info'),
        ),
        migrations.AlterField(
            model_name='googlecalendarconfig',
            name='additional_info',
            field=models.JSONField(blank=True, null=True, verbose_name='Additional Info'),
        ),
        migrations.AlterField(
            model_name='googleintegrationsetting',
            name='additional_info',
            field=models.JSONField(blank=True, null=True, verbose_name='Additional Info'),
        ),
        migrations.AlterField(
            model_name='useravailability',
            name='additional_info',
            field=models.JSONField(blank=True, null=True, verbose_name='Additional Info'),
        ),
        migrations.AlterField(
            model_name='usercalendarpreference',
            name='additional_info',
            field=models.JSONField(blank=True, null=True, verbose_name='Additional Info'),
        ),
    ]
