# Generated by Django 6.0.4 on 2026-08-28 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadences', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cadencefollowup',
            options={'ordering': ['followup_number', 'order', 'created_at'], 'verbose_name': 'Cadence Follow Up', 'verbose_name_plural': 'Cadence Follow Ups'},
        ),
        migrations.AlterField(
            model_name='cadence',
            name='additional_info',
            field=models.JSONField(blank=True, null=True, verbose_name='Additional Info'),
        ),
        migrations.AlterField(
            model_name='cadencecondition',
            name='additional_info',
            field=models.JSONField(blank=True, null=True, verbose_name='Additional Info'),
        ),
        migrations.AlterField(
            model_name='cadencefollowup',
            name='additional_info',
            field=models.JSONField(blank=True, null=True, verbose_name='Additional Info'),
        ),
        migrations.AlterField(
            model_name='cadencefollowup',
            name='branch_from',
            field=models.ForeignKey(blank=True, help_text='Set when this step was created from a specific parent card’s + (next stage).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_children', to='cadences.cadencefollowup', verbose_name='Branched From'),
        ),
        migrations.AlterField(
            model_name='cadencefollowup',
            name='followup_number',
            field=models.PositiveSmallIntegerField(default=1, help_text='Stage number (1 = first follow-up).', verbose_name='Follow Up'),
        ),
        migrations.AlterField(
            model_name='cadencefollowup',
            name='followup_type',
            field=models.CharField(choices=[('task', 'Task'), ('call', 'Call'), ('email', 'Email')], max_length=20, verbose_name='Follow Up Type'),
        ),
        migrations.AlterField(
            model_name='cadencefollowup',
            name='to',
            field=models.TextField(blank=True, help_text='Recipients for this step. Choose user/email fields from the record', null=True, verbose_name='Mail To'),
        ),
    ]
