# Generated by Django 6.0.4 on 2026-09-02 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadences', '0003_alter_cadencefollowup_options_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='cadence',
                    name='created_at',
                    field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At'),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='CREATE INDEX IF NOT EXISTS "cadences_cadence_created_at_b2e18945" ON "cadences_cadence" ("created_at")',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='cadence',
                    name='is_active',
                    field=models.BooleanField(db_index=True, default=True, verbose_name='Is Active'),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='CREATE INDEX IF NOT EXISTS "cadences_cadence_is_active_ace8b4e7" ON "cadences_cadence" ("is_active")',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='cadencecondition',
                    name='created_at',
                    field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At'),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='CREATE INDEX IF NOT EXISTS "cadences_cadencecondition_created_at_e5d7d918" ON "cadences_cadencecondition" ("created_at")',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='cadencecondition',
                    name='is_active',
                    field=models.BooleanField(db_index=True, default=True, verbose_name='Is Active'),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='CREATE INDEX IF NOT EXISTS "cadences_cadencecondition_is_active_05ab0e68" ON "cadences_cadencecondition" ("is_active")',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='cadencefollowup',
                    name='created_at',
                    field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At'),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='CREATE INDEX IF NOT EXISTS "cadences_cadencefollowup_created_at_74ebcf80" ON "cadences_cadencefollowup" ("created_at")',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='cadencefollowup',
                    name='is_active',
                    field=models.BooleanField(db_index=True, default=True, verbose_name='Is Active'),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='CREATE INDEX IF NOT EXISTS "cadences_cadencefollowup_is_active_ff959672" ON "cadences_cadencefollowup" ("is_active")',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
    ]
