# Generated by Django 6.0.4 on 2026-07-31 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0003_alter_contact_address_city_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="assistant_phone",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="secondary_phone",
        ),
        migrations.AddField(
            model_name="contact",
            name="assistant_contact_number",
            field=models.CharField(
                blank=True,
                max_length=40,
                null=True,
                verbose_name="Assistant Contact Number",
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="contact_number",
            field=models.CharField(
                blank=True, max_length=40, null=True, verbose_name="Contact Number"
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="secondary_contact_number",
            field=models.CharField(
                blank=True,
                max_length=40,
                null=True,
                verbose_name="Secondary Contact Number",
            ),
        ),
    ]
