# Generated by Django 6.0.4 on 2026-09-17 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_alter_contact_contact_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='bintang_contact_id',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, unique=True, verbose_name='Bintang Contact ID'),
        ),
    ]
