# Generated by Django 6.0.4 on 2026-07-31 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_account_account_source"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="phone",
        ),
        migrations.AddField(
            model_name="account",
            name="contact_number",
            field=models.CharField(
                blank=True, max_length=40, verbose_name="Contact Number"
            ),
        ),
    ]
