# Generated by Django 6.0.4 on 2026-08-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0004_horillamail_send_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horillamail',
            name='additional_info',
            field=models.JSONField(blank=True, null=True, verbose_name='Additional Info'),
        ),
        migrations.AlterField(
            model_name='horillamailattachment',
            name='additional_info',
            field=models.JSONField(blank=True, null=True, verbose_name='Additional Info'),
        ),
        migrations.AlterField(
            model_name='horillamailconfiguration',
            name='additional_info',
            field=models.JSONField(blank=True, null=True, verbose_name='Additional Info'),
        ),
        migrations.AlterField(
            model_name='horillamailconfiguration',
            name='outlook_api_endpoint',
            field=models.URLField(blank=True, null=True, verbose_name='Microsoft Graph API Endpoint'),
        ),
        migrations.AlterField(
            model_name='horillamailconfiguration',
            name='outlook_authorization_url',
            field=models.URLField(blank=True, null=True, verbose_name='OAuth Authorization Endpoint'),
        ),
        migrations.AlterField(
            model_name='horillamailconfiguration',
            name='outlook_redirect_uri',
            field=models.URLField(blank=True, null=True, verbose_name='Redirect URI'),
        ),
        migrations.AlterField(
            model_name='horillamailconfiguration',
            name='outlook_token_url',
            field=models.URLField(blank=True, null=True, verbose_name='OAuth Token Endpoint'),
        ),
        migrations.AlterField(
            model_name='horillamailtemplate',
            name='additional_info',
            field=models.JSONField(blank=True, null=True, verbose_name='Additional Info'),
        ),
        migrations.AlterField(
            model_name='horillamailtemplate',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Template Title'),
        ),
    ]
