# Generated by Django 6.0.4 on 2026-08-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunities", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opportunity",
            name="name",
            field=models.CharField(max_length=120, verbose_name="Opportunity Name"),
        ),
    ]
