# Generated by Django 6.0.4 on 2026-08-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0002_alter_opportunity_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opportunityteammember',
            options={'verbose_name': 'Opportunity Team Member', 'verbose_name_plural': 'Opportunity Team Members'},
        ),
        migrations.AlterField(
            model_name='defaultopportunitymember',
            name='additional_info',
            field=models.JSONField(blank=True, null=True, verbose_name='Additional Info'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='additional_info',
            field=models.JSONField(blank=True, null=True, verbose_name='Additional Info'),
        ),
        migrations.AlterField(
            model_name='opportunitycontactrole',
            name='additional_info',
            field=models.JSONField(blank=True, null=True, verbose_name='Additional Info'),
        ),
        migrations.AlterField(
            model_name='opportunitysettings',
            name='additional_info',
            field=models.JSONField(blank=True, null=True, verbose_name='Additional Info'),
        ),
        migrations.AlterField(
            model_name='opportunitysettings',
            name='allow_all_users_in_splits',
            field=models.BooleanField(default=False, help_text='When enabled, users can assign splits to any active user in the company, not just opportunity team members. This allows adding new members while editing splits.', verbose_name='Let Users Add Members to Opportunity Teams While Editing Splits'),
        ),
        migrations.AlterField(
            model_name='opportunitysplit',
            name='additional_info',
            field=models.JSONField(blank=True, null=True, verbose_name='Additional Info'),
        ),
        migrations.AlterField(
            model_name='opportunitysplittype',
            name='additional_info',
            field=models.JSONField(blank=True, null=True, verbose_name='Additional Info'),
        ),
        migrations.AlterField(
            model_name='opportunitystage',
            name='additional_info',
            field=models.JSONField(blank=True, null=True, verbose_name='Additional Info'),
        ),
        migrations.AlterField(
            model_name='opportunityteam',
            name='additional_info',
            field=models.JSONField(blank=True, null=True, verbose_name='Additional Info'),
        ),
        migrations.AlterField(
            model_name='opportunityteammember',
            name='additional_info',
            field=models.JSONField(blank=True, null=True, verbose_name='Additional Info'),
        ),
    ]
