# Generated by Django 6.0.4 on 2026-09-17 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0005_alter_opportunity_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='bintang_sale_id',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True, unique=True, verbose_name='Bintang Sale ID'),
        ),
    ]
