# Generated by Django 6.0.4 on 2026-09-26 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0006_opportunity_bintang_sale_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_periode', models.CharField(help_text='Mis. Oktober 2026, Kuartal IV', max_length=100)),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField()),
                ('target_nilai', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('target_jumlah_order', models.PositiveIntegerField(default=0)),
                ('catatan', models.CharField(blank=True, default='', max_length=255)),
                ('dibuat', models.DateTimeField(auto_now_add=True)),
                ('diubah', models.DateTimeField(auto_now=True)),
                ('dibuat_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-tanggal_mulai', 'sales__first_name'],
            },
        ),
    ]
