# Generated by Django 6.0.4 on 2026-08-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_leadassignmentcondition_leadassignmentmatchcriteria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtoleadconfig',
            name='additional_info',
            field=models.JSONField(blank=True, null=True, verbose_name='Additional Info'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='additional_info',
            field=models.JSONField(blank=True, null=True, verbose_name='Additional Info'),
        ),
        migrations.AlterField(
            model_name='leadassignmentcondition',
            name='additional_info',
            field=models.JSONField(blank=True, null=True, verbose_name='Additional Info'),
        ),
        migrations.AlterField(
            model_name='leadassignmentmatchcriteria',
            name='additional_info',
            field=models.JSONField(blank=True, null=True, verbose_name='Additional Info'),
        ),
        migrations.AlterField(
            model_name='leadassignmentrule',
            name='additional_info',
            field=models.JSONField(blank=True, null=True, verbose_name='Additional Info'),
        ),
        migrations.AlterField(
            model_name='leadcaptureform',
            name='additional_info',
            field=models.JSONField(blank=True, null=True, verbose_name='Additional Info'),
        ),
        migrations.AlterField(
            model_name='leadcaptureform',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ar', 'Arabic'), ('de', 'German'), ('fr', 'French'), ('fa', 'Persian')], default='en', max_length=10, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='leadstatus',
            name='additional_info',
            field=models.JSONField(blank=True, null=True, verbose_name='Additional Info'),
        ),
    ]
