# Generated by Django 6.0.4 on 2026-09-02 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_alter_emailtoleadconfig_additional_info_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='emailtoleadconfig',
                    name='created_at',
                    field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At'),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='CREATE INDEX IF NOT EXISTS "leads_emailtoleadconfig_created_at_6215eb54" ON "leads_emailtoleadconfig" ("created_at")',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='emailtoleadconfig',
                    name='is_active',
                    field=models.BooleanField(db_index=True, default=True, verbose_name='Is Active'),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='CREATE INDEX IF NOT EXISTS "leads_emailtoleadconfig_is_active_e80cd321" ON "leads_emailtoleadconfig" ("is_active")',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='lead',
                    name='created_at',
                    field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At'),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='CREATE INDEX IF NOT EXISTS "leads_lead_created_at_a7f0123f" ON "leads_lead" ("created_at")',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='lead',
                    name='is_active',
                    field=models.BooleanField(db_index=True, default=True, verbose_name='Is Active'),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='CREATE INDEX IF NOT EXISTS "leads_lead_is_active_dceaab61" ON "leads_lead" ("is_active")',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='lead',
                    name='is_convert',
                    field=models.BooleanField(blank=True, db_index=True, default=False, editable=False, null=True),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='CREATE INDEX IF NOT EXISTS "leads_lead_is_convert_a77cc4af" ON "leads_lead" ("is_convert")',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='leadassignmentcondition',
                    name='created_at',
                    field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At'),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='CREATE INDEX IF NOT EXISTS "leads_leadassignmentcondition_created_at_d84f3875" ON "leads_leadassignmentcondition" ("created_at")',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='leadassignmentcondition',
                    name='is_active',
                    field=models.BooleanField(db_index=True, default=True, verbose_name='Is Active'),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='CREATE INDEX IF NOT EXISTS "leads_leadassignmentcondition_is_active_a36380f5" ON "leads_leadassignmentcondition" ("is_active")',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='leadassignmentmatchcriteria',
                    name='created_at',
                    field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At'),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='CREATE INDEX IF NOT EXISTS "leads_leadassignmentmatchcriteria_created_at_1bd88772" ON "leads_leadassignmentmatchcriteria" ("created_at")',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='leadassignmentmatchcriteria',
                    name='is_active',
                    field=models.BooleanField(db_index=True, default=True, verbose_name='Is Active'),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='CREATE INDEX IF NOT EXISTS "leads_leadassignmentmatchcriteria_is_active_40b0d32f" ON "leads_leadassignmentmatchcriteria" ("is_active")',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='leadassignmentrule',
                    name='created_at',
                    field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At'),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='CREATE INDEX IF NOT EXISTS "leads_leadassignmentrule_created_at_2b9882a5" ON "leads_leadassignmentrule" ("created_at")',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='leadassignmentrule',
                    name='is_active',
                    field=models.BooleanField(db_index=True, default=True, verbose_name='Is Active'),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='CREATE INDEX IF NOT EXISTS "leads_leadassignmentrule_is_active_ccd51f22" ON "leads_leadassignmentrule" ("is_active")',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='leadcaptureform',
                    name='created_at',
                    field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At'),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='CREATE INDEX IF NOT EXISTS "leads_leadcaptureform_created_at_05a20a67" ON "leads_leadcaptureform" ("created_at")',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='leadcaptureform',
                    name='is_active',
                    field=models.BooleanField(db_index=True, default=True, verbose_name='Is Active'),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='CREATE INDEX IF NOT EXISTS "leads_leadcaptureform_is_active_16821291" ON "leads_leadcaptureform" ("is_active")',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='leadstatus',
                    name='created_at',
                    field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At'),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='CREATE INDEX IF NOT EXISTS "leads_leadstatus_created_at_6165ec21" ON "leads_leadstatus" ("created_at")',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='leadstatus',
                    name='is_active',
                    field=models.BooleanField(db_index=True, default=True, verbose_name='Is Active'),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='CREATE INDEX IF NOT EXISTS "leads_leadstatus_is_active_5d41ec67" ON "leads_leadstatus" ("is_active")',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='leadstatus',
                    name='is_final',
                    field=models.BooleanField(db_index=True, default=False, verbose_name='Is Final Stage'),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='CREATE INDEX IF NOT EXISTS "leads_leadstatus_is_final_0bcf67a5" ON "leads_leadstatus" ("is_final")',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
    ]
