# Generated by Django 6.0.4 on 2026-10-06 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_alter_emailtoleadconfig_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadcaptureform',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ar', 'Arabic'), ('de', 'German'), ('fr', 'French'), ('fa', 'Persian'), ('id', 'Indonesian')], default='en', max_length=10, verbose_name='Language'),
        ),
    ]
