# Generated by Django 6.0.4 on 2026-08-28 10:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationcondition',
            name='additional_info',
            field=models.JSONField(blank=True, null=True, verbose_name='Additional Info'),
        ),
        migrations.AlterField(
            model_name='automationrunlog',
            name='additional_info',
            field=models.JSONField(blank=True, null=True, verbose_name='Additional Info'),
        ),
        migrations.AlterField(
            model_name='horillaautomation',
            name='additional_info',
            field=models.JSONField(blank=True, null=True, verbose_name='Additional Info'),
        ),
        migrations.AlterField(
            model_name='horillaautomation',
            name='also_sent_to',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Also Send To'),
        ),
        migrations.AlterField(
            model_name='horillaautomation',
            name='mail_to',
            field=models.TextField(help_text="Specify recipients for email/notifications. Supports:\n- Direct email: user@example.com\n- Self: 'self' (person who triggered)\n- Instance fields: 'instance.owner.email', 'instance.created_by', 'instance.owner'\n- Multiple: comma-separated (e.g., 'self, instance.owner.email, admin@example.com')\n\nFor notifications: Use user fields directly (e.g., 'instance.owner') or email addresses.\nThe system will find users by email if an email address is provided.", verbose_name='Mail to/Notify To'),
        ),
    ]
