# Generated by Django 6.0.4 on 2026-09-02 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring_rules', '0002_alter_emailactivityscoring_additional_info_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='emailactivityscoring',
                    name='created_at',
                    field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At'),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='CREATE INDEX IF NOT EXISTS "scoring_rules_emailactivityscoring_created_at_dbeda099" ON "scoring_rules_emailactivityscoring" ("created_at")',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='emailactivityscoring',
                    name='is_active',
                    field=models.BooleanField(db_index=True, default=True, verbose_name='Is Active'),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='CREATE INDEX IF NOT EXISTS "scoring_rules_emailactivityscoring_is_active_9c0c8a4a" ON "scoring_rules_emailactivityscoring" ("is_active")',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='scoringcondition',
                    name='created_at',
                    field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At'),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='CREATE INDEX IF NOT EXISTS "scoring_rules_scoringcondition_created_at_7cfba6c0" ON "scoring_rules_scoringcondition" ("created_at")',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='scoringcondition',
                    name='is_active',
                    field=models.BooleanField(db_index=True, default=True, verbose_name='Is Active'),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='CREATE INDEX IF NOT EXISTS "scoring_rules_scoringcondition_is_active_4210fdb8" ON "scoring_rules_scoringcondition" ("is_active")',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='scoringcriterion',
                    name='created_at',
                    field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At'),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='CREATE INDEX IF NOT EXISTS "scoring_rules_scoringcriterion_created_at_2bc1628a" ON "scoring_rules_scoringcriterion" ("created_at")',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='scoringcriterion',
                    name='is_active',
                    field=models.BooleanField(db_index=True, default=True, verbose_name='Is Active'),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='CREATE INDEX IF NOT EXISTS "scoring_rules_scoringcriterion_is_active_3236d4e5" ON "scoring_rules_scoringcriterion" ("is_active")',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='scoringrule',
                    name='created_at',
                    field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At'),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='CREATE INDEX IF NOT EXISTS "scoring_rules_scoringrule_created_at_c2d5987e" ON "scoring_rules_scoringrule" ("created_at")',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='scoringrule',
                    name='is_active',
                    field=models.BooleanField(db_index=True, default=True, verbose_name='Is Active'),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='CREATE INDEX IF NOT EXISTS "scoring_rules_scoringrule_is_active_a5197f6f" ON "scoring_rules_scoringrule" ("is_active")',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
    ]
